apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-djeo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-djeo
    app.kubernetes.io/part-of: service-registry
  name: apicurio-registry-djeo
  namespace: shbose-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: apicurio-registry-djeo
status:
  loadBalancer: {}
